### PR TITLE
Do not strip away special characters from project names

### LINKED ISSUE #118: Generators strip away '/' and '-' from project names when creating go.mod
### Current Behavior

If you create an application or library using the following command:

```bash
nx g @nx-go/nx-go:application apps/backend-info
```

The go.mod file will be initialized as follows:

```txt
module workspace/appsbackendinfo

go 1.22
```

### Expected Behavior

If you create an application or library using the following command:

```bash
nx g @nx-go/nx-go:application apps/backend-info
```

The go.mod file should be initialized as follows:

```txt
module workspace/apps/backend-info

go 1.22
```

### Github Repo

_No response_

### Steps to Reproduce

1. Run `nx g @nx-go/nx-go:application apps/backend-info`
2. Observe the module property in the created `go.mod` file

### Nx Report

```shell
Node   : 20.12.2
OS     : darwin-arm64
pnpm   : 9.0.6

nx                 : 18.3.4
@nx/js             : 18.3.4
@nx/jest           : 18.3.4
@nx/linter         : 18.3.4
@nx/eslint         : 18.3.4
@nx/workspace      : 18.3.4
@nx/angular        : 18.3.4
@nx/devkit         : 18.3.4
@nx/esbuild        : 18.3.4
@nx/eslint-plugin  : 18.3.4
@nx/plugin         : 18.3.4
@nrwl/tao          : 18.3.4
@nx/web            : 18.3.4
@nx/webpack        : 18.3.4
nx-cloud           : 18.0.1
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx-go/nx-go
---------------------------------------
Community plugins:
@fortawesome/angular-fontawesome : 0.14.1
@nx-go/nx-go                     : 3.0.0
```

### nx.json

```json
{
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "targetDefaults": {
    "build": {
      "dependsOn": ["^build"],
      "inputs": ["production", "^production"],
      "cache": true
    },
    "@nx-go/nx-go:lint": {
      "cache": true
    },
    "@nx-go/nx-go:test": {
      "cache": true
    },
    "@nx-go/nx-go:build": {
      "inputs": [
        "production",
        "^production",
        {
          "runtime": "go version"
        }
      ],
      "cache": true
    },
    "@nx/eslint:lint": {
      "inputs": [
        "default",
        "{workspaceRoot}/.eslintrc.json",
        "{workspaceRoot}/.eslintignore",
        "{workspaceRoot}/eslint.config.js"
      ],
      "cache": true
    },
    "@nx/jest:jest": {
      "inputs": ["default", "^production", "{workspaceRoot}/jest.preset.js"],
      "cache": true,
      "options": {
        "passWithNoTests": true
      },
      "configurations": {
        "ci": {
          "ci": true,
          "codeCoverage": true
        }
      }
    },
    "@nx/js:tsc": {
      "cache": true,
      "dependsOn": ["^build"],
      "inputs": ["production", "^production"]
    },
    "@nx/esbuild:esbuild": {
      "cache": true,
      "dependsOn": ["^build"],
      "inputs": ["production", "^production"]
    }
  },
  "namedInputs": {
    "default": ["{projectRoot}/**/*", "sharedGlobals"],
    "production": [
      "default",
      "!{projectRoot}/**/?(*.)+(spec|test).[jt]s?(x)?(.snap)",
      "!{projectRoot}/tsconfig.spec.json",
      "!{projectRoot}/jest.config.[jt]s",
      "!{projectRoot}/src/test-setup.[jt]s",
      "!{projectRoot}/test-setup.[jt]s",
      "!{projectRoot}/.eslintrc.json",
      "!{projectRoot}/eslint.config.js"
    ],
    "sharedGlobals": ["{workspaceRoot}/go.work"]
  },
  "generators": {
    "@nx/angular:application": {
      "style": "scss",
      "linter": "eslint",
      "unitTestRunner": "jest",
      "e2eTestRunner": "none"
    },
    "@nx/angular:library": {
      "linter": "eslint",
      "unitTestRunner": "jest"
    },
    "@nx/angular:component": {
      "style": "scss"
    }
  },
  "useInferencePlugins": false,
  "defaultBase": "master",
  "plugins": ["@nx-go/nx-go"]
}
```

### Failure Logs

_No response_

### Go Version

1.22

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by utarwyn**
This PR modifies the project names used in the generators to improve the Go module and package names in the generated files.

Resolves #118

### CODE REVIEW

File: packages/nx-go/src/generators/library/generator.ts [hunk 1]
```diff
@@ -54,7 +54,7 @@ export default async function libraryGenerator(
   if (isGoWorkspace(tree)) {
     createGoMod(
       tree,
-      `${options.npmScope}/${options.moduleName}`,
+      `${options.npmScope}/${options.name}`,
```
Comment (phillipCouto) [inline packages/nx-go/src/generators/library/generator.ts:57]: **suggestion:** This should be the project root.

This way the import path would have the same path as the file path to the project folder. Not sure if this how others build out their go workspaces but this is how we define our module names in `go.mod` files. 

Its not a big deal if we want to leave it but if we execute a command like the following:

```bash
nx g @nx-go/nx-go:library workflows --directory libs/feature/admin
```

It will create a go.mod file like so:

```txt
module [npmScope]/workflows

go 1.22
```

If I want to add a workflows module to a different feature this will create a collision.

Comment (phillipCouto) [reply packages/nx-go/src/generators/library/generator.ts:57]: I know in the original issue the example used the name as a path but I wanted to check what happens when a directory is provided.

Comment (utarwyn) [reply packages/nx-go/src/generators/library/generator.ts:57]: Awesome suggestion, indeed my solution was not ideal. I will change that, thank you for the feedback!

File: packages/nx-go/src/generators/application/generator.ts [hunk 2]
```diff
@@ -60,11 +60,7 @@ export default async function applicationGenerator(
   generateFiles(tree, join(__dirname, 'files'), options.projectRoot, options);
 
   if (isGoWorkspace(tree)) {
-    createGoMod(
-      tree,
-      `${options.npmScope}/${options.moduleName}`,
-      options.projectRoot
-    );
+    createGoMod(tree, options.projectRoot, options.projectRoot);
```
Comment (utarwyn) [inline packages/nx-go/src/generators/application/generator.ts:63]: To do not to break other calls in the project, for the moment I've set the same value in both parameters.

Comment (phillipCouto) [reply packages/nx-go/src/generators/application/generator.ts:63]: Ok, I will review tonight ☺️

**Review by phillipCouto — APPROVED** [review]
Looks good @utarwyn, thank you for the fix :smile:.

**Comment by utarwyn** [comment]
Thank you for the feedback 💯
